#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/springtestdb_rest_mysql
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        format_sql: 'true'
#    hibernate:
#      ddl-auto: create

spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/restfulkafka?currentSchema=customers
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    username: postgres
    password: password
    initialize: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: create-drop

